
language: c


os:
  - linux

sudo: true


install:
  - curl -R -O http://www.lua.org/ftp/lua-5.4.3.tar.gz
  - tar zxf lua-5.4.3.tar.gz
  - cd lua-5.4.3
  - make linux test
  - cd ..
  - sudo apt-get install -y luarocks
  - sudo luarocks install moonscript --dev
  - moon -v

script:
  - cd test
  - for f in *.moon; do printf "\n\u001b[32m====== $f \u001b[0m\n\n"; moon $f; done
